FROM adoptopenjdk/openjdk8-openj9:alpine-slim

ARG WATERFALL_CDN_URL
ENV WATERFALL_CDN_URL=$WATERFALL_CDN_URL

ARG WATERFALL_SUBSERVERS_ROLE
ENV WATERFALL_SUBSERVERS_ROLE=$WATERFALL_SUBSERVERS_ROLE

RUN mkdir -p /waterfall
ADD ./config /waterfall/

COPY ./build.sh /build.sh
RUN sh /build.sh

COPY ./run.sh /run.sh

ENV JAVA_MEMORY=512M
ENV JAVA_ARGS=

ENV WATERFALL_REDIS_IP=
ENV WATERFALL_SUBDATA_IP=

CMD ["sh", "/run.sh"]
