Settings:
  Version: 19w35b
Lang:
  Bungee.Feature.Smart-Fallback: '&6Returning from $str$: &r$msg$'
  Bungee.Feature.Smart-Fallback.Result: '&6You are now on $str$.'
  Bungee.Ping.Offline: '&6&l[&e&lWarning&6&l] &7Backend server(s) are not running'
  Bungee.Server.Current: '&6You are currently connected to $str$'
  Bungee.Server.Available: '&6You may connect to the following servers at this tRime:'
  Bungee.Server.List: '&6$str$'
  Bungee.Server.Hover: |-
    $int$ player(s)
    &oClick to connect to the server
  Bungee.Server.Divider: '&6, '
  Bungee.Server.Offline: '&cThe specified server is not currently running.'
  Bungee.Server.Invalid: '&cThe specified server does not exist.'
  Bungee.List.Format: '&a[$str$] &e($int$)&r: '
  Bungee.List.List: '&f$str$'
  Bungee.List.Divider: '&f, '
  Bungee.List.Total: 'Total players online: $int$'
  Command.Generic.Player-Only: "&cSubServers &4&l\xbb&c Console cannot run this command"
  Command.Generic.Console-Only: "&cSubServers &4&l\xbb&c This command is for console\
    \ use only"
  Command.Generic.Usage: "&7SubServers &8&l\xbb&7 Usage: &f$str$"
  Command.Generic.Exception: "&cSubServers &4&l\xbb&c An unexpected exception has\
    \ occurred while parsing this command"
  Command.Generic.Invalid-Subcommand: "&cSubServers &4&l\xbb&c Unknown sub-command:\
    \ $str$"
  Command.Generic.Invalid-Permission: "&cSubServers &4&l\xbb&c You need &4&n$str$&c\
    \ to use this command"
  Command.Generic.Unknown-Proxy: "&cSubServers &4&l\xbb&c There is no proxy with that\
    \ name"
  Command.Generic.Unknown-Host: "&cSubServers &4&l\xbb&c There is no host with that\
    \ name"
  Command.Generic.Unknown-Group: "&cSubServers &4&l\xbb&c There is no group with that\
    \ name"
  Command.Generic.Unknown-Server: "&cSubServers &4&l\xbb&c There is no server with\
    \ that name"
  Command.Generic.Unknown-SubServer: "&cSubServers &4&l\xbb&c There is no subserver\
    \ with that name"
  Command.Help.Header: "&7SubServers &8&l\xbb&7 Command Help:"
  Command.Help.Help: '   &7Help:&f $str$'
  Command.Help.List: '   &7List:&f $str$'
  Command.Help.Version: '   &7Version:&f $str$'
  Command.Help.Info: '   &7Info:&f $str$'
  Command.Help.Host.Create: '   &7Create Server:&f $str$'
  Command.Help.SubServer.Start: '   &7Start Server:&f $str$'
  Command.Help.SubServer.Restart: '   &7Restart Server:&f $str$'
  Command.Help.SubServer.Stop: '   &7Stop Server:&f $str$'
  Command.Help.SubServer.Terminate: '   &7Terminate Server:&f $str$'
  Command.Help.SubServer.Command: '   &7Command Server:&f $str$'
  Command.Help.SubServer.Update: '   &7Update Server:&f $str$'
  Command.Version: "&7SubServers &8&l\xbb&7 These are the platforms and versions that\
    \ are running &f$str$&7:"
  Command.Version.Outdated: '&7$name$ &f$str$ &7is available. You are $int$ version(s)
    behind.'
  Command.Version.Latest: '&7You are on the latest version.'
  Command.List.Group-Header: "&7SubServers &8&l\xbb&7 Group/Server List:"
  Command.List.Host-Header: "&7SubServers &8&l\xbb&7 Host/SubServer List:"
  Command.List.Server-Header: "&7SubServers &8&l\xbb&7 Server List:"
  Command.List.Proxy-Header: "&7SubServers &8&l\xbb&7 Proxy List:"
  Command.List.Header: '&7: '
  Command.List.Divider: '&7, '
  Command.List.Empty: '&7(none)'
  Command.Info: "&7SubServers &8&l\xbb&7 Info on $str$&7: &r"
  Command.Info.Unknown: "&cSubServers &4&l\xbb&c There is no object with that name"
  Command.Info.Unknown-Type: "&cSubServers &4&l\xbb&c There is no object type with\
    \ that name"
  Command.Info.Unknown-Proxy: "&cSubServers &4&l\xbb&c There is no proxy with that\
    \ name"
  Command.Info.Unknown-Host: "&cSubServers &4&l\xbb&c There is no host with that name"
  Command.Info.Unknown-Group: "&cSubServers &4&l\xbb&c There is no group with that\
    \ name"
  Command.Info.Unknown-Server: "&cSubServers &4&l\xbb&c There is no server with that\
    \ name"
  Command.Info.Format: ' -> &7$str$&7: &r'
  Command.Info.List: '  - '
  Command.Start: "&aSubServers &2&l\xbb&a Starting SubServer"
  Command.Start.Unknown: "&cSubServers &4&l\xbb&c There is no Server with that name"
  Command.Start.Invalid: "&cSubServers &4&l\xbb&c That Server is not a SubServer"
  Command.Start.Host-Unavailable: "&cSubServers &4&l\xbb&c That SubServer's Host is\
    \ not available"
  Command.Start.Host-Disabled: "&cSubServers &4&l\xbb&c That SubServer's Host is not\
    \ enabled"
  Command.Start.Server-Unavailable: "&cSubServers &4&l\xbb&c That SubServer is not\
    \ available"
  Command.Start.Server-Disabled: "&cSubServers &4&l\xbb&c That SubServer is not enabled"
  Command.Start.Server-Incompatible: "&cSubServers &4&l\xbb&c That SubServer cannot\
    \ start while these server(s) are running: &4$str$"
  Command.Start.Running: "&cSubServers &4&l\xbb&c That SubServer is already running"
  Command.Restart: "&aSubServers &2&l\xbb&a Stopping SubServer"
  Command.Restart.Finish: "&aSubServers &2&l\xbb&a Starting SubServer"
  Command.Restart.Unknown: "&cSubServers &4&l\xbb&c There is no Server with that name"
  Command.Restart.Invalid: "&cSubServers &4&l\xbb&c That Server is not a SubServer"
  Command.Restart.Disappeared: "&cSubServers &4&l\xbb&c Could not restart server:\
    \ That SubServer has disappeared"
  Command.Restart.Host-Unavailable: "&cSubServers &4&l\xbb&c Could not restart server:\
    \ That SubServer's Host is no longer available"
  Command.Restart.Host-Disabled: "&cSubServers &4&l\xbb&c Could not restart server:\
    \ That SubServer's Host is no longer enabled"
  Command.Restart.Server-Unavailable: "&cSubServers &4&l\xbb&c Could not restart server:\
    \ That SubServer is no longer available"
  Command.Restart.Server-Disabled: "&cSubServers &4&l\xbb&c Could not restart server:\
    \ That SubServer is no longer enabled"
  Command.Restart.Server-Incompatible: "&cSubServers &4&l\xbb&c Could not restart\
    \ server: That SubServer cannot start while these server(s) are running: &4$str$"
  Command.Stop: "&aSubServers &2&l\xbb&a Stopping SubServer"
  Command.Stop.Unknown: "&cSubServers &4&l\xbb&c There is no Server with that name"
  Command.Stop.Invalid: "&cSubServers &4&l\xbb&c That Server is not a SubServer"
  Command.Stop.Not-Running: "&cSubServers &4&l\xbb&c That SubServer is not running"
  Command.Terminate: "&aSubServers &2&l\xbb&a Stopping SubServer"
  Command.Terminate.Unknown: "&cSubServers &4&l\xbb&c There is no Server with that\
    \ name"
  Command.Terminate.Invalid: "&cSubServers &4&l\xbb&c That Server is not a SubServer"
  Command.Terminate.Not-Running: "&cSubServers &4&l\xbb&c That SubServer is not running"
  Command.Command: "&aSubServers &2&l\xbb&a Sending command to SubServer"
  Command.Command.Unknown: "&cSubServers &4&l\xbb&c There is no Server with that name"
  Command.Command.Invalid: "&cSubServers &4&l\xbb&c That Server is not a SubServer"
  Command.Command.Not-Running: "&cSubServers &4&l\xbb&c That SubServer is not running"
  Command.Creator: "&aSubServers &2&l\xbb&a Creating SubServer"
  Command.Creator.Exists: "&cSubServers &4&l\xbb&c There is already a SubServer with\
    \ that name"
  Command.Creator.Unknown-Host: "&cSubServers &4&l\xbb&c There is no Host with that\
    \ name"
  Command.Creator.Host-Unavailable: "&cSubServers &4&l\xbb&c That Host is not available"
  Command.Creator.Host-Disabled: "&cSubServers &4&l\xbb&c That Host is not enabled"
  Command.Creator.Unknown-Template: "&cSubServers &4&l\xbb&c There is no Template\
    \ with that name"
  Command.Creator.Template-Disabled: "&cSubServers &4&l\xbb&c That Template is not\
    \ enabled"
  Command.Creator.Version-Required: "&cSubServers &4&l\xbb&c That Template requires\
    \ a Minecraft Version to be specified"
  Command.Creator.Invalid-Port: "&cSubServers &4&l\xbb&c Invalid Port Number"
  Command.Update: "&aSubServers &2&l\xbb&a Updating SubServer"
  Command.Update.Unknown: "&cSubServers &4&l\xbb&c There is no Server with that name"
  Command.Update.Invalid: "&cSubServers &4&l\xbb&c That Server is not a SubServer"
  Command.Update.Host-Unavailable: "&cSubServers &4&l\xbb&c That SubServer's Host\
    \ is not available"
  Command.Update.Host-Disabled: "&cSubServers &4&l\xbb&c That SubServer's Host is\
    \ not enabled"
  Command.Update.Server-Unavailable: "&cSubServers &4&l\xbb&c That SubServer is not\
    \ available"
  Command.Update.Running: "&cSubServers &4&l\xbb&c Cannot update servers while they\
    \ are still running"
  Command.Update.Unknown-Template: "&cSubServers &4&l\xbb&c We don't know which template\
    \ created that SubServer"
  Command.Update.Template-Disabled: "&cSubServers &4&l\xbb&c That SubServer's Template\
    \ is not enabled"
  Command.Update.Template-Invalid: "&cSubServers &4&l\xbb&c That SubServer's Template\
    \ does not support server updating"
  Command.Update.Version-Required: "&cSubServers &4&l\xbb&c That SubServer's Template\
    \ requires a Minecraft Version to be specified"
  Interface.Generic.Back: '&cBack'
  Interface.Generic.Back-Arrow: '&e&l<--'
  Interface.Generic.Next-Arrow: '&e&l-->'
  Interface.Generic.Undo: '&6Undo'
  Interface.Generic.Downloading: "&7SubServers &8&l\xbb&7 Downloading:&f $str$"
  Interface.Generic.Downloading.Title: Downloading...
  Interface.Generic.Downloading.Title-Color: '&b'
  Interface.Generic.Downloading.Title-Color-Alt: '&3'
  Interface.Generic.Downloading.Response: '&eWaiting for response'
  Interface.Generic.Invalid-Permission: '&4You need &n$str$'
  Interface.Proxy-Menu.Proxy-Player-Count: '&2$int$ Player(s) Online'
  Interface.Proxy-Menu.Proxy-Master: '&8Master Proxy'
  Interface.Proxy-Menu.Proxy-SubData: '&9SubData Only'
  Interface.Proxy-Menu.Proxy-Redis: '&7Redis Only'
  Interface.Proxy-Menu.Proxy-Disconnected: '&4Disconnected'
  Interface.Host-Menu.Title: Host Menu
  Interface.Host-Menu.Host-Unavailable: '&4Unavailable'
  Interface.Host-Menu.Host-Disabled: '&4Disabled'
  Interface.Host-Menu.Host-Server-Count: '&9$int$ Server(s)'
  Interface.Host-Menu.No-Hosts: '&c&oThere are No Hosts'
  Interface.Host-Menu.Group-Menu: '&6&lView Servers by Group'
  Interface.Host-Menu.Server-Menu: '&a&lView Servers'
  Interface.Host-Admin.Title: Host/$str$
  Interface.Host-Admin.Creator: '&eCreate a SubServer'
  Interface.Host-Admin.SubServers: '&bView SubServers'
  Interface.Host-Admin.Plugins: '&bPlugins...'
  Interface.Host-Creator.Title: Host/$str$/Create
  Interface.Host-Creator.Edit-Name: Change Name
  Interface.Host-Creator.Edit-Name.Title: |-
    &eSubCreator
    &6Enter a Name for this Server
  Interface.Host-Creator.Edit-Name.Message: "&eSubCreator &6&l\xbb&e Enter a Name\
    \ for this Server via Chat"
  Interface.Host-Creator.Edit-Name.Exists: "&cSubCreator &4&l\xbb&c There is already\
    \ a SubServer with that name"
  Interface.Host-Creator.Edit-Name.Exists-Title: |-
    &eSubCreator
    &cThere is already a SubServer with that name
  Interface.Host-Creator.Edit-Name.Invalid: "&cSubCreator &4&l\xbb&c Invalid Server\
    \ Name"
  Interface.Host-Creator.Edit-Name.Invalid-Title: |-
    &eSubCreator
    &cInvalid Server Name
  Interface.Host-Creator.Edit-Template: Change Server Template
  Interface.Host-Creator.Edit-Template.Title: Host/$str$/Templates
  Interface.Host-Creator.Edit-Template.No-Templates: '&c&oThere are No Templates'
  Interface.Host-Creator.Edit-Version: Change Server Version
  Interface.Host-Creator.Edit-Version.Title: |-
    &eSubCreator
    &6Enter a Server Version
  Interface.Host-Creator.Edit-Version.Message: "&eSubCreator &6&l\xbb&e Enter a Server\
    \ Version via Chat"
  Interface.Host-Creator.Edit-Port: Change Server Port
  Interface.Host-Creator.Edit-Port.Title: |-
    &eSubCreator
    &6Enter a Port Number
  Interface.Host-Creator.Edit-Port.Message: "&eSubCreator &6&l\xbb&e Enter a Port\
    \ Number via Chat"
  Interface.Host-Creator.Edit-Port.Invalid: "&cSubCreator &4&l\xbb&c Invalid Port\
    \ Number"
  Interface.Host-Creator.Edit-Port.Invalid-Title: |-
    &eSubCreator
    &cInvalid Port Number
  Interface.Host-Creator.Submit: '&eCreate SubServer'
  Interface.Host-Creator.Form-Incomplete: '&4Buttons above must be green'
  Interface.Host-Plugin.Title: Host/$str$/Plugins
  Interface.Host-Plugin.No-Plugins: '&c&oThere are No Plugins Available'
  Interface.Host-SubServer.Title: Host/$str$/SubServers
  Interface.Group-Menu.Title: Group Menu
  Interface.Group-Menu.Group-Server-Count: '&9$int$ Server(s)'
  Interface.Group-Menu.No-Groups: '&c&oThere are No Groups'
  Interface.Group-Menu.Server-Menu: '&a&lView All Servers'
  Interface.Group-SubServer.Title: Group/$str$/Servers
  Interface.Server-Menu.Title: Server Menu
  Interface.Server-Menu.Server-Player-Count: '&2$int$ Player(s) Online'
  Interface.Server-Menu.Server-External: '&7External Server'
  Interface.Server-Menu.SubServer-Temporary: '&9Temporary'
  Interface.Server-Menu.SubServer-Offline: '&6Offline'
  Interface.Server-Menu.SubServer-Incompatible: '&4Incompatible with $str$'
  Interface.Server-Menu.SubServer-Unavailable: '&4Unavailable'
  Interface.Server-Menu.SubServer-Disabled: '&4Disabled'
  Interface.Server-Menu.SubServer-Invalid: '&4Cannot be managed by SubServers'
  Interface.Server-Menu.No-Servers: '&c&oThere are No Servers'
  Interface.Server-Menu.Host-Menu: '&b&lView Hosts'
  Interface.SubServer-Admin.Title: SubServer/$str$
  Interface.SubServer-Admin.Start: '&aStart SubServer'
  Interface.SubServer-Admin.Start.Title: '&aStarting SubServer'
  Interface.SubServer-Admin.Stop: '&cStop SubServer'
  Interface.SubServer-Admin.Stop.Title: '&cStopping $str$'
  Interface.SubServer-Admin.Terminate: '&4Terminate SubServer'
  Interface.SubServer-Admin.Terminate.Title: '&cTerminating $str$'
  Interface.SubServer-Admin.Command: '&bSend a Command to the SubServer'
  Interface.SubServer-Admin.Command.Title: |-
    &eSubServers
    &6Enter a Command to send via Chat
  Interface.SubServer-Admin.Command.Message: "&eSubServers &6&l\xbb&e Enter a Command\
    \ to send via Chat"
  Interface.SubServer-Admin.Update: '&eUpdate SubServer'
  Interface.SubServer-Admin.Update.Title: |-
    &eSubServers
    &6Enter a Server Version to update to
  Interface.SubServer-Admin.Update.Message: "&eSubServers &6&l\xbb&e Enter a Server\
    \ Version to update to via Chat"
  Interface.SubServer-Admin.Plugins: '&bPlugins...'
  Interface.SubServer-Plugin.Title: SubServer/$str$/Plugins
  Interface.SubServer-Plugin.No-Plugins: '&c&oThere are No Plugins Available'
